use fitbit;

DROP TABLE IF EXISTS `device`;
CREATE TABLE `device` (
  `ID` varchar(20) NOT NULL,
  `DEVICEDATA` JSON DEFAULT NULL,
  `LASTSYNCTIME` datetime DEFAULT NULL,
  `REFRESHTOKEN` varchar(1000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  `ACCESSTOKEN` varchar(1000) CHARACTER SET latin1 COLLATE latin1_bin DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT fitbitid_unique UNIQUE (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `fitbitresponse`;
CREATE TABLE `fitbitresponse` (
  `ID` bigint(20) NOT NULL,
  `POSTEDON` datetime DEFAULT CURRENT_TIMESTAMP,
  `FITBITSTEPS` bigint(20) DEFAULT NULL,
  `ONDATE` date NOT NULL,
  `RESPONSEDATA` JSON NOT NULL,
  `DEVICEID` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  CONSTRAINT fitbitid_unique UNIQUE (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE `activities` (
  `LOGID` bigint(20) NOT NULL,
  `FITBITID` varchar(20) NOT NULL,
  PRIMARY KEY (`LOGID`)
)